allowBuilds:
  core-js-pure: false
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - "@cloudflare/vitest-plugin@1.3.0"
  - miniflare@5.20260926.0-alpha
  - wrangler@4.142.0 || 4.143.0
  - "@cloudflare/codemods@0.2.1"
  - cf@1.0.0-beta.5
overrides:
  "hono@4": 4.13.8
  "undici@7": 7.29.1
